from pydantic import BaseModel, Field
from typing import Optional, List, Union
from datetime import datetime
from enum import Enum

class ContentStatus(str, Enum):
    INGESTED = "ingested"
    PROCESSING = "processing"
    READY = "ready"
    APPROVED = "approved"

class HookSuggestion(BaseModel):
    alternative_number: int = Field(description="Alternative suggestion ID (e.g. 1, 2, 3)")
    visual_hook: str = Field(description="Description of the visual actions in the first 3 seconds")
    text_on_screen: str = Field(description="Hook text overlay on screen")

class ContentBase(BaseModel):
    video_drive_url: str = Field(description="Google Drive shareable link to original video file")
    audio_cached_url: Optional[str] = Field(default=None, description="Local path or cloud cache link to the extracted lightweight audio")
    status: ContentStatus = Field(default=ContentStatus.INGESTED, description="State of the content in pipeline")
    transcription: Optional[str] = Field(default=None, description="Literal transcription generated by Content-Brain")
    hooks_sugeridos: List[Union[str, HookSuggestion]] = Field(default=[], description="Suggested hooks list (either raw text or structured objects)")
    copy_final: Optional[str] = Field(default=None, description=" strategic final copy formatted under Afterbow specifications")
    fecha_creacion: datetime = Field(default_factory=datetime.utcnow, description="Timestamp when the DIT agent ingested this file")

class Content(ContentBase):
    id: str = Field(description="Firestore subcollection document ID")
    cliente_id: str = Field(description="Document ID of the parent client")

class ContentUpdate(BaseModel):
    status: Optional[ContentStatus] = None
    audio_cached_url: Optional[str] = None
    transcription: Optional[str] = None
    hooks_sugeridos: Optional[List[Union[str, HookSuggestion]]] = None
    copy_final: Optional[str] = None
